### ISSUE TITLE
[contact-form] auth applicative

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/e2esdk#25]
## Description

Pour compléter l'exemple contact-form :

 - fournir une authentification (keycloak?) pour limiter l'accès aux données
 - une fois loggé côté app, logger le user sur e2esdk pour recup les clés
 - se deco de e2esdk quand logout côté app ?
 - utiliser hasura & les rôles pour limiter les accès aux données
    - `agent` : create form, read own/shared? form submissions, rw own/shared? form comments
    - `anonymous` : create submission only
 - pouvoir inviter des utilisateurs, existants ou pas, pour partager l'accès aux soumission d'un formulaire

(on a un example d'integration keycloak/hasura sur [template](https://github.com/SocialGouv/template))

**Comment by franky47** [comment]
Ca serait pas mal d'avoir plusieurs sous-catégories d'agents, pour illustrer le déchiffrement partiel de réponses (champs sensibles limités à des _"super-agents"_, et le reste accessible à tout agent).

**Comment by revolunet** [comment]
in progress in https://github.com/SocialGouv/support/issues/398
