### ISSUE TITLE
[keygen]: packaging

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/e2esdk#34]
testing on OSX/Node@18

`npx @socialgouv/e2esdk-keygen --help` or installing in project and `yarn keygen --help` throw this error

<img width="679" alt="Capture d’écran 2023-01-25 à 16 04 17" src="https://user-images.githubusercontent.com/124937/214598621-fbbeef69-7ca0-4e13-98aa-5aa7b08020c9.png">

**Comment by franky47** [comment]
Fixed in c0e7f9e0a0e62465a247599aea4157199ae67265

If anyone knows a better way to get the package.json associated to a bin script, following the symbolink link, I'm all ears. In the mean time, I'm removing the version display.

**Comment by revolunet** [comment]
fixed, thanks
