### ISSUE TITLE
npm keygen opaque

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/e2esdk#54]
Looks like it doesnt output the result

<img width="653" alt="Capture d’écran 2023-04-12 à 11 10 21" src="https://user-images.githubusercontent.com/124937/231410922-c9dc334f-015f-41f6-b3f7-d2a5a9032c6f.png">

**Comment by franky47** [comment]
It works on my side but it looks like the command is expanded into something different, what's your PNPM version ?

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1174092/231411950-83af044d-5880-478d-8937-8d093f51e8be.png">

**Comment by revolunet** [comment]
étrange, pareil sur la branche beta, avec pnpm@8 🤔 

<img width="724" alt="Capture d’écran 2023-04-12 à 12 08 57" src="https://user-images.githubusercontent.com/124937/231426691-e0c136ba-4332-4993-988a-0ccb62de93c8.png">

**Comment by franky47** [comment]
Tu as nettoyé ton node_modules et réinstallé les deps après le branch switch?

**Comment by revolunet** [comment]
je viens de retester avec un RAZ du node_modules et pareil 🤔

**Comment by revolunet** [comment]
ca fonctionne bien depuis une fresh install après un `pnpm build:npm`
